# File: embedding/generate_tests.py
import json
import os
import requests
from dotenv import load_dotenv

# Load Azure credentials
load_dotenv()
AZURE_INSTANCE = os.getenv("AZURE_OPENAI_INSTANCE_NAME")
AZURE_DEPLOYMENT = os.getenv("AZURE_OPENAI_API_DEPLOYMENT_NAME")
AZURE_KEY = os.getenv("AZURE_OPENAI_API_KEY")

assert AZURE_INSTANCE and AZURE_DEPLOYMENT and AZURE_KEY, "Azure OpenAI credentials are missing."

CHAT_URL = f"https://{AZURE_INSTANCE}.openai.azure.com/openai/deployments/{AZURE_DEPLOYMENT}/chat/completions?api-version=2023-05-15"
HEADERS = {
    "Content-Type": "application/json",
    "api-key": AZURE_KEY,
}

# Load prompts
with open("generated-prompts.json", "r") as f:
    prompts = json.load(f)

output_dir = "test-output"
os.makedirs(output_dir, exist_ok=True)

# Send prompts to Azure GPT-4 and save tests
for item in prompts:
    prompt_text = item["prompt"]
    print(f"📤 Sending: {item['id']}")

    try:
        res = requests.post(
            CHAT_URL,
            headers=HEADERS,
            json={
                "messages": [
                    {"role": "system", "content": "You are an expert in writing high-quality, idiomatic Jest test cases."},
                    {"role": "user", "content": prompt_text},
                ],
                "temperature": 0.3,
            },
        )
        res.raise_for_status()
        completion = res.json()["choices"][0]["message"]["content"]

        file_name = item["id"].replace("/", "_").replace("::", "__") + ".test.ts"
        file_path = os.path.join(output_dir, file_name)
        with open(file_path, "w") as f:
            f.write("// Auto-generated by Azure OpenAI\n\n")
            f.write(completion)

        print(f"✅ Test written to {file_path}")

    except Exception as e:
        print(f"❌ Failed to generate test for {item['id']}: {e}")
